version: 2

sources:
  - name: sales_source
    database: sales_db
    schema: main
    tables:
      - name: sales_daily
      - name: sales_hourly
      - name: sales_monthly
      - name: sales_weekly
